services:
  app:
    build: .
    ports:
      - "8000:80"  # El puerto 80 del contenedor se expone en el puerto 8000 del host
      - "8080:8080"  # Para el servidor de sockets
    networks:
      - laravel-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/nodo1.php # Llama al archivo nodo1.php
    networks:
      - laravel-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/nodo2.php # Llama al archivo nodo2.php
    networks:
      - laravel-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/nodo3.php # Llama al archivo nodo3.php
    networks:
      - laravel-network

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/nodo4.php # Llama al archivo nodo4.php
    networks:
      - laravel-network

  node5:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/nodo5.php # Llama al archivo nodo5.php
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
